name: send-file-tg
description: Send file to Telegram

inputs:
  tg-token:
    description: 'Telegram Token'
    required: true
  tg-chat:
    description: 'Telegram chat id'
    required: true
  thread-id:
    description: 'Telegram chat id'
    required: true
  file:
    description: 'Path to file'
    required: true
  text:
    description: 'Report message'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send file
      shell: bash
      run: |
        curl -X POST "https://api.telegram.org/bot${{ inputs.tg-token }}/sendDocument" \
        -F chat_id=${{ inputs.tg-chat }} \
        -F message_thread_id=${{ inputs.thread-id }} \
        -F document=@${{ inputs.file }} \
        -F parse_mode="Markdown" \
        -F caption="${{ inputs.text }}"

