name: create-google-services
description: Create google-services.json from secret

runs:
  using: "composite"
  steps:
    - name: Create google-services.json
      shell: bash
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
