name: "Run KtLint"
description: "Runs KtLint, merges SARIF reports and generates Markdown + HTML reports"

inputs:
  gradle-flags:
    description: "Gradle flags"
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: Run KtLint
      shell: bash
      run: |
        ./gradlew ktlintCheck --continue ${{ inputs.gradle-flags }}

    - name: Collect SARIF files
      shell: bash
      run: |
        mkdir -p ktlint-sarif
        find . -type f -path "*/build/reports/ktlint/*/*.sarif" -exec cp {} ktlint-sarif/ \;

    - name: Merge SARIF files
      shell: bash
      run: |
        if compgen -G "ktlint-sarif/*.sarif" > /dev/null; then
          jq -s '
            {
              version: "2.1.0",
              runs: [
                {
                  tool: .[0].runs[0].tool,
                  results: (map(.runs[].results) | add)
                }
              ]
            }
          ' ktlint-sarif/*.sarif > merged-ktlint.sarif
        else
          echo "No SARIF files found."
          echo '{}' > merged-ktlint.sarif
        fi

    - name: Generate detailed Markdown report
      shell: bash
      run: |
        echo "# KtLint Detailed Report" > ktlint-report.md
        echo "" >> ktlint-report.md

        total=0
        declare -A moduleIssues
        declare -A moduleDetails

        for file in $(find . -type f -path "*/build/reports/ktlint/*/*.sarif"); do
          module=$(echo "$file" | sed -E 's#^\./##' | sed -E 's#/build/reports/ktlint/.*##' | sed 's#/#:#g')

          count=$(jq '[.runs[].results[]] | length' "$file")

          if [ "$count" -gt 0 ]; then
            moduleIssues["$module"]=$(( ${moduleIssues["$module"]} + count ))
            total=$((total + count))

            details=$(jq -r '
              .runs[].results[] |
              "- `" + .locations[0].physicalLocation.artifactLocation.uri + ":" +
              (.locations[0].physicalLocation.region.startLine|tostring) + ":" +
              (.locations[0].physicalLocation.region.startColumn|tostring) +
              "`  \n  " + .message.text +
              " (" + .ruleId + ")"' "$file")

            moduleDetails["$module"]+="$details"$'\n'
          fi
        done

        echo "## ðŸ”Ž Total issues: $total" >> ktlint-report.md
        echo "" >> ktlint-report.md

        if [ "$total" -gt 0 ]; then
          echo "## ðŸ“¦ Issues by module" >> ktlint-report.md
          echo "" >> ktlint-report.md
          echo "| Module | Issues |" >> ktlint-report.md
          echo "|--------|--------|" >> ktlint-report.md

          for module in "${!moduleIssues[@]}"; do
            echo "| $module | ${moduleIssues[$module]} |" >> ktlint-report.md
          done

          echo "" >> ktlint-report.md
          echo "## ðŸ“ Detailed issues" >> ktlint-report.md
          echo "" >> ktlint-report.md

          for module in "${!moduleDetails[@]}"; do
            echo "### $module" >> ktlint-report.md
            echo "" >> ktlint-report.md
            echo "${moduleDetails[$module]}" >> ktlint-report.md
            echo "" >> ktlint-report.md
          done
        else
          echo "âœ… No issues found ðŸŽ‰" >> ktlint-report.md
        fi

        cat ktlint-report.md >> $GITHUB_STEP_SUMMARY
