name: "Render Markdown to HTML"
description: "Converts Markdown file to styled HTML"

inputs:
  input-file:
    description: "Path to markdown file"
    required: true

  output-file:
    description: "Path to output HTML file"
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Pandoc
      uses: pandoc/actions/setup@v1

    - name: Create CSS
      shell: bash
      run: |
        cat <<EOF > style.css
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          margin: 40px;
          background-color: #f8f9fa;
        }
        h1, h2, h3 {
          color: #24292e;
        }
        table {
          border-collapse: collapse;
          width: 100%;
          margin-bottom: 20px;
        }
        table, th, td {
          border: 1px solid #d0d7de;
        }
        th, td {
          padding: 8px 12px;
          text-align: left;
        }
        th {
          background-color: #f6f8fa;
        }
        code {
          background-color: #f6f8fa;
          padding: 2px 4px;
          border-radius: 4px;
        }
        @media (prefers-color-scheme: dark) {
          body {
            background: #0d1117;
            color: #c9d1d9;
          }
          th {
            background-color: #161b22;
          }
          table, th, td {
            border: 1px solid #30363d;
          }
        }
        EOF

    - name: Convert Markdown to HTML
      shell: bash
      run: |
        pandoc "${{ inputs.input-file }}" \
          -f gfm \
          -t html \
          -s \
          --css=style.css \
          -o "${{ inputs.output-file }}"
