name: Build App release

on:
  workflow_dispatch:
  push:
    branches:
      - 'test/**'
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  ANDROID_SDK_ROOT: /usr/lib/android-sdk
  API_TOKEN: ${{ secrets.API_TOKEN }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

jobs:
  validate-version:
    name: Validate and extract version
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.extract.outputs.version_name }}
      version_code: ${{ steps.extract.outputs.version_code }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract version from branch
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ (v\.[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION_WITH_PREFIX="${BASH_REMATCH[1]}"
            VERSION_NAME="${VERSION_WITH_PREFIX#v.}"

            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NAME"
            VERSION_CODE=$((MAJOR * 1000000 + MINOR * 1000 + PATCH))

            echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
            echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

            echo "Detected version: $VERSION_NAME ($VERSION_CODE)"
          else
            echo "❌ Branch must end with v.X.Y.Z"
            exit 1
          fi

  build-aab:
    name: Build signed AAB
    runs-on: ubuntu-latest
    needs: validate-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/android-setup
      - name: Decode Keystore
        run: echo "${{ secrets.JKS_KS }}" | base64 -d > app/release.jks
      - name: Build Release Bundle
        run: |
          ./gradlew bundleRelease \
            -PversionCode=${{ needs.validate-release.outputs.version_code }} \
            -PversionName=${{ needs.validate-release.outputs.version_name }} \
            $GRADLE_FLAGS
        env:
          KEYSTORE_PASSWORD: ${{ secrets.JKS_KS_PASS }}
          KEY_ALIAS: ${{ secrets.JKS_ALIAS }}
          KEY_PASSWORD: ${{ secrets.JKS_KEY_PASS }}
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab

  publish-play:
    name: Publish to Play Internal
    runs-on: ubuntu-latest
    needs: build-aab
    steps:
      - name: Download signed aab
        uses: actions/download-artifact@v4
        with:
          name: app-release-aab
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.PLAY_PACKAGE_NAME }}
          releaseFiles: app-release.aab
          track: internal
          status: draft
